apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: filenet-template
    tags: filenet
  name: filenet-template
objects:
  - apiVersion: icp4a.ibm.com/v1
    kind: ICP4ACluster
    metadata:
      namespace: cp4ba
      name: icp4adeploy
      labels:
        app.kubernetes.io/instance: ibm-dba
        app.kubernetes.io/managed-by: ibm-dba
        app.kubernetes.io/name: ibm-dba
        release: 23.0.2
    spec:
      datasource_configuration:
        dc_os_datasources:
          - dc_database_type: "sqlserver"
            dc_os_label: cicdos${OS_NUMBER}
            dc_common_os_datasource_name: FNCICDOS${OS_NUMBER}DS
            dc_common_os_xa_datasource_name: FNCICDOS${OS_NUMBER}DSXA
            database_servername: ${DB2_HOST}
            database_name: CICDOS${OS_NUMBER}DB
            database_port: "1433"
      initialize_configuration:
        ic_obj_store_creation:
          object_stores:
          - oc_cpe_obj_store_display_name: CICDOS${OS_NUMBER}
            oc_cpe_obj_store_symb_name: CICDOS${OS_NUMBER}
            oc_cpe_obj_store_conn:
              name: CICDOS${OS_NUMBER}_dbconnection
              dc_os_datasource_name: FNCICDOS${OS_NUMBER}DS
              dc_os_xa_datasource_name: FNCICDOS${OS_NUMBER}DSXA
            oc_cpe_obj_store_admin_user_groups:
            - "cpadmins"
            oc_cpe_obj_store_enable_content_event_emitter: true
            oc_cpe_obj_store_addons_list:
              - "{CE460ADD-0000-0000-0000-000000000004}" # 5.2.1 Base Application Extensions (default)
              - "{CE460ADD-0000-0000-0000-000000000001}" # 5.2.1 Base Content Engine Extensions (default)
              - "{CE460ADD-0000-0000-0000-000000000003}" # (default)
              - "{CE511ADD-0000-0000-0000-000000000006}" # (default)
              - "{CE460ADD-0000-0000-0000-000000000008}" # (default)
              - "{CE460ADD-0000-0000-0000-000000000007}" # (default)
              - "{CE460ADD-0000-0000-0000-000000000009}" # (default)
              - "{CE460ADD-0000-0000-0000-00000000000A}" # (default)
              - "{CE460ADD-0000-0000-0000-00000000000B}" # (default)
              - "{CE460ADD-0000-0000-0000-00000000000D}" # (default)
              - "{CE511ADD-0000-0000-0000-00000000000F}" # (default)
              - "{CE511ADD-0000-0000-0000-000000000010}" # 5.2.1 Teamspace Extensions
              - "{CE511ADD-0000-0000-0000-000000000015}" # 5.2.1 Custom Role Extensions
              - "{CE521ADD-0000-0000-0000-000000000016}" # 5.2.1 Social Collaboration Role Extensions
              - "{CE552ADD-0000-0000-0000-00000000001C}" # 5.5.2 Core Collaboration Extensions
              - "{CE551ADD-0000-0000-0000-000000000011}" # 5.5.1 Social Collaboration Base Extensions
              - "{CE554ADD-0000-0000-0000-000000000021}" # 5.5.4 Event-Driven External Service Invocation Extensions
        ic_css_index_area:
          - index_area_name: cicdos${OS_NUMBER}_index_area
            object_store_name: CICDOS${OS_NUMBER}
        ic_enable_cbr:
          - object_store_name: CICDOS${OS_NUMBER}
        ic_icn_init_info:
          icn_repos:
          - add_repo_id: CICDOS${OS_NUMBER}
            add_repo_os_sym_name: CICDOS${OS_NUMBER}
            add_repo_os_dis_name: CICDOS${OS_NUMBER}
          icn_desktop:
          - add_desktop_id: CICDOS${OS_NUMBER}
            add_desktop_name: CICDOS${OS_NUMBER}
            add_desktop_description: This is CICDOS${OS_NUMBER} desktop
            add_desktop_repo_id: CICDOS${OS_NUMBER}             
      ########################################################################
      ######## IBM FileNet Content Manager Verification configuration ######
      ########################################################################
      ## After the initialization process (see section above), the verification process will take place.
      ## The verification process ensures that the FNCM and BAN components are functioning correctly.  The verification
      ## process includes creation of a CPE folder, a CPE document, a CBR search, verifying the workflow configuration,
      ## and validation of the ICN desktop.
      verify_configuration:
        vc_cpe_verification:
          vc_cpe_cbr:
          - cbr_cpe_obj_store_name: CICDOS${OS_NUMBER}
        vc_icn_verification:
          - vc_icn_repository: CICDOS${OS_NUMBER}
            vc_icn_desktop_id: CICDOS${OS_NUMBER}
parameters:
  - name: OS_NUMBER
  - name: DB2_HOST