apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 23.0.2
  name: icp4adeploy
spec:
  datasource_configuration:
    dc_os_datasources:
    - database_name: CICDOS2DB
      database_port: "1433"
      database_servername: mssql.mssql.svc.cluster.local
      dc_common_os_datasource_name: FNCICDOS2DS
      dc_common_os_xa_datasource_name: FNCICDOS2DSXA
      dc_database_type: sqlserver
      dc_os_label: cicdos2
  initialize_configuration:
    ic_css_index_area:
    - index_area_name: cicdos2_index_area
      object_store_name: CICDOS2
    ic_enable_cbr:
    - object_store_name: CICDOS2
    ic_icn_init_info:
      icn_desktop:
      - add_desktop_description: This is CICDOS2 desktop
        add_desktop_id: CICDOS2
        add_desktop_name: CICDOS2
        add_desktop_repo_id: CICDOS2
      icn_repos:
      - add_repo_id: CICDOS2
        add_repo_os_dis_name: CICDOS2
        add_repo_os_sym_name: CICDOS2
    ic_obj_store_creation:
      object_stores:
      - oc_cpe_obj_store_addons_list:
        - '{CE460ADD-0000-0000-0000-000000000004}'
        - '{CE460ADD-0000-0000-0000-000000000001}'
        - '{CE460ADD-0000-0000-0000-000000000003}'
        - '{CE511ADD-0000-0000-0000-000000000006}'
        - '{CE460ADD-0000-0000-0000-000000000008}'
        - '{CE460ADD-0000-0000-0000-000000000007}'
        - '{CE460ADD-0000-0000-0000-000000000009}'
        - '{CE460ADD-0000-0000-0000-00000000000A}'
        - '{CE460ADD-0000-0000-0000-00000000000B}'
        - '{CE460ADD-0000-0000-0000-00000000000D}'
        - '{CE511ADD-0000-0000-0000-00000000000F}'
        - '{CE511ADD-0000-0000-0000-000000000010}'
        - '{CE511ADD-0000-0000-0000-000000000015}'
        - '{CE521ADD-0000-0000-0000-000000000016}'
        - '{CE552ADD-0000-0000-0000-00000000001C}'
        - '{CE551ADD-0000-0000-0000-000000000011}'
        - '{CE554ADD-0000-0000-0000-000000000021}'
        oc_cpe_obj_store_admin_user_groups:
        - cpadmins
        oc_cpe_obj_store_conn:
          dc_os_datasource_name: FNCICDOS2DS
          dc_os_xa_datasource_name: FNCICDOS2DSXA
          name: CICDOS2_dbconnection
        oc_cpe_obj_store_display_name: CICDOS2
        oc_cpe_obj_store_enable_content_event_emitter: true
        oc_cpe_obj_store_symb_name: CICDOS2
  verify_configuration:
    vc_cpe_verification:
      vc_cpe_cbr:
      - cbr_cpe_obj_store_name: CICDOS2
    vc_icn_verification:
    - vc_icn_desktop_id: CICDOS2
      vc_icn_repository: CICDOS2
